// Mocks generated by Mockito 5.4.4 from annotations
// in iman_mate_mobile_app/test/features/prayer/prayer_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:iman_mate_mobile_app/features/prayer/models/performance_models.dart'
    as _i2;
import 'package:iman_mate_mobile_app/features/prayer/models/prayer_models.dart'
    as _i5;
import 'package:iman_mate_mobile_app/features/prayer/services/location_service.dart'
    as _i6;
import 'package:iman_mate_mobile_app/features/prayer/services/prayer_api_service.dart'
    as _i7;
import 'package:iman_mate_mobile_app/features/prayer/services/prayer_local_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePrayerScoreConfigModel_0 extends _i1.SmartFake
    implements _i2.PrayerScoreConfigModel {
  _FakePrayerScoreConfigModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PrayerLocalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrayerLocalService extends _i1.Mock
    implements _i3.PrayerLocalService {
  MockPrayerLocalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> savePrayerDay(_i5.PrayerDayModel? day) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePrayerDay,
          [day],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i5.PrayerDayModel? getPrayerDay(DateTime? date) =>
      (super.noSuchMethod(Invocation.method(
        #getPrayerDay,
        [date],
      )) as _i5.PrayerDayModel?);

  @override
  List<_i5.PrayerDayModel> getDaysForMonth(
    int? month,
    int? year,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDaysForMonth,
          [
            month,
            year,
          ],
        ),
        returnValue: <_i5.PrayerDayModel>[],
      ) as List<_i5.PrayerDayModel>);

  @override
  _i4.Future<void> saveConfig(_i2.PrayerScoreConfigModel? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConfig,
          [config],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.PrayerScoreConfigModel getConfig() => (super.noSuchMethod(
        Invocation.method(
          #getConfig,
          [],
        ),
        returnValue: _FakePrayerScoreConfigModel_0(
          this,
          Invocation.method(
            #getConfig,
            [],
          ),
        ),
      ) as _i2.PrayerScoreConfigModel);

  @override
  _i4.Future<void> saveMonthlySummary(_i2.MonthlySummaryModel? summary) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMonthlySummary,
          [summary],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.MonthlySummaryModel? getMonthlySummary(
    int? month,
    int? year,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getMonthlySummary,
        [
          month,
          year,
        ],
      )) as _i2.MonthlySummaryModel?);
}

/// A class which mocks [LocationLocalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationLocalService extends _i1.Mock
    implements _i6.LocationLocalService {
  MockLocationLocalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveLocation(_i5.UserLocationModel? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocation,
          [location],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [PrayerApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrayerApiService extends _i1.Mock implements _i7.PrayerApiService {
  MockPrayerApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, _i5.PrayerTimesModel>> getPrayerTimesCalendar(
    double? lat,
    double? lng,
    int? month,
    int? year,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrayerTimesCalendar,
          [
            lat,
            lng,
            month,
            year,
          ],
        ),
        returnValue: _i4.Future<Map<String, _i5.PrayerTimesModel>>.value(
            <String, _i5.PrayerTimesModel>{}),
      ) as _i4.Future<Map<String, _i5.PrayerTimesModel>>);
}
